from time import sleep

print('Narrator: King Kong embarks out of the bar, and beings to walk. After some time, he strolls into the neighborhood of Fruity Fields, where he meets his crew, the Strawhat Pirates.')
sleep(3)
print('Narrator: Kai giggles stupidly.\n Kai:"Gee wiz Kongy! I\'ve always wondered, why are you doing this anyways? Awww shucks!" ')
sleep(2)
print('Narrator: Owen also stupidly giggles. \nOwen:"For realsies Kingy! I wanna know also! Duih!" ')
sleep(2)
print('Gudrun Norberto Porvy-Wulfhard: "Same."')
sleep(2)
print('Australian Henriques:"Bloody Yanks!" He says, in his australian accent. He\'s very australian. "I\'d kangarooy love too know also!"')
sleep(2)
print('Lil Nas X: "Yeah. This answer is for the champions."')
sleep(3)
print('King Kong: "Don\'t worry about that yet Kai... you\'ll know when the time comes...')
sleep(3)
print('Narrator: The brave Kong traverses on, embarking on his grand quest along with his two "sidekicks". He never really wanted to bring them along, but they insisted on tagging along.')
sleep(3)
print('King Kong: "First, we have too ')