import blackjack
from time import sleep
import classes
from FIGHT import fight
delay=0
players_health=100

print("Narrator: Welcome to King Kong's Greatest Ace! The Bird Mafia has taken over Bananaland, and is using their corrupt values and powerful associates to poop on as many cars as possible. As King Kong, you will need to traverse the city and find a way to defeat the Bird Mafia once and for all. However, you will need to fight them not with guns, knives, or fists, but with knowledge, cunningness, and deception in a game of blackjack. Now, as you enter Bananaland for the first time, looking to create change, you walk into a local pub and find Big Bird standing there, serving customers.")
tutorial = input("Is this your first time playing? Y/N: ")
if tutorial == "Y":
    print("Narrator: Okay. As previously stated, you will need to defeat your enemies through the card game known as blackjack. Big Bird will now give you a brief explanation of how to play Blackjack.")
    sleep(delay)
    print("Narrator: You now stumble into Big Bird's Bar, where Big Bird is waiting at the bar, ready to teach you how to play.")
    sleep(delay)
    print("Big Bird: Hello! I will now teach you how to play blackjack. While blackjack is very simple, I will teach you the rules of the game and explain some easy strategies to make you better.")
    sleep(delay)
    print("Big Bird: Blackjack is a simple game. Your goal is to get as close to a total of 21 without going over. The game will start with you and a dealer sitting across from one another. The dealer will give both you and him/herself a face-down card and a face-up card. You can now read your face down card.")
    sleep(delay)
    print("Big Bird: After reading your two cards, add their values together, and determine whether or not you need more cards. If you are not sure what your total value is, remember that numbers 1-9 are taken at their face value and the number 10 and all face cards (jack, queen, and king) are worth 10. Aces are unique because they can be valued at either 1 OR 11 based on your situation. You get to decide.")
    sleep(delay)
    print("Big Bird: A second or two after you read your cards, the dealer will ask you if you want to HIT or STAND. HIT means you will draw another card, and STAND means that you are done receiving cards. You can HIT as many times as you want, but if you go over a total of 21, you BUST and are automatically out.")
    sleep(delay)
    print("Big Bird: Furthermore, if you STAND but have less total points than the dealer, you lose. Finally, if you immediately draw an ace and a jack, you get BLACKJACK and automatically win the round.")
    sleep(delay)
    print("Big Bird: OK! You now have a basic idea of how blackjack works.")
    
    
elif tutorial == "N":
    print('Big Bird: That wasn\'t nice. I\'ll give you a second chance.')
tutorial_game = input("Big Bird: Would you like to play a warmup round with me to make sure you understand the rules? Y/N: ")
if tutorial_game == "Y":
        mode = "NORMAL" 
        print('Okie dokie then! Let\'s play!')
        blackjack.blackjack()
        if blackjack.c.wl=='loss':
             print('Big bird: Good game buckaroo! I won! ')
        elif blackjack.c.wl=='tie':
             print('Big Bird: Close one buddy! We tied! ')
        else:
             print('Big Bird:Oh, you won! Good job!')
elif tutorial_game == "N":
    mode = "HARD" #Yeah yeah. This was never used in the end. If this was the full game, this would basically trigger the true ending.
    print("Big Bird: That was very rude of you.")
    
sleep(delay)
print("Narrator: You stroll out of the bar, eventually making your way to the neighborhood of Fruity Fields. There, you run into your sidekick, Australian Henriques.")
sleep(delay)
print("Australian Henriques: Bloody Yanks! I don't know why you're back here in Bananaland, with your bounty and all, but you should go.")
sleep(delay)
print("King Kong: Never mind that, Australian Henriques. Walk with me, there's someone I want you to meet.")
sleep(delay)
print("Narrator: The pair stroll on, passing signs of the dreadful Bird Mafia, the ones who put the bounty on you, all the way.")
sleep(delay)
print("Narrator: Together, you and Australian Henriques eventually make it a small hut with a door made of beads. You force the door open, revealing a sign that says, The Seer's Hut.")
sleep(delay)
print("Australian Henriques: What is this place? It looks like the route to the underworld.")
sleep(delay)
print("King Kong: You'll see who lives here soon enough. Now, allow me to call him.")
sleep(delay)
print("Narrator: You draw a pentagram in the sand, at which point the Seer stumbles out of the shadows and looks right into Australian Henriques' eyes.")
sleep(delay)
print("Australian Henriques: Crikey. That's one damn creepy Yank.")
sleep(delay)
print("Lil Nas X (Seer): Well... if it isn't King Kong. Come down to this old town road again, eh? I can't help a fugitive like you, sorry.")
sleep(delay)
print("King Kong: You can help me. We both know you can. Australian Henriques and I need to bring about the drums of liberation.")
sleep(delay)
print("Lil Nas X: Still talking in riddles, eh?")
sleep(delay)
print("King Kong: You know exactly what I mean.")
sleep(delay)
print("Lil Nas X: I suppose I do. Well, if you want my help, you'll have to beat me in combat. My magic orb, it's for the champions.")
sleep(delay)
print("King Kong: If you want a challenge, then bring it. Your skills are the least of my worries.")
sleep(delay)
print("Lil Nas X: Eh? I haven't lost since I began, yeah.")
sleep(delay)
print(f"Narrator: In Bananaland, when you accept a challenge from an opponent, their stats will flash on your screen. Furthermore, you currently have {players_health} health. You must gamble a certain amount of health, and you will either lose it or absorb your opponents health. Your opponent will automatically gamble the same amount of health as you, unless they are a hit opponent, who you will have to defeat once for each number of hits.")
sleep(delay)
print("Narrator: Normally, you will have to gamble a certain amount of health to lower an enemy. However, Lil Nas X is a special hit boss, so your gamble will automatically be 10 per 1 hit.")
sleep(delay)

Lil_Nas_X = classes.Boss("Lil_Nas_X", 1, "Magic Orb", "Fruity Fields", False)
sleep(delay)

fight(players_health,Lil_Nas_X,"Lil Nas X: Still undefeated, yeah, cause I haven't lost since I began. You can keep trying to beat me, but you won't be able to.","Lil Nas X: Nice try, but this one is for the champions. And I haven't lost since I began yeah.","Lil Nas X: How could you have possibly defeated me, when I haven't lost since I began, yeah? I guess I'll help you now that you have proven yourself worthy.","I am getting rusty huh? Guess I got to hit the old town road again.")

sleep(delay)
print("Lil Nas X: Okay, so you said you need to bring about the drums of liberation. How exactly do you plan to take down the bird mafia?")
sleep(delay)
print("King Kong: Well, after extensive research and some help from Australian Henriques, who went undercover into the Bird Mafia, I have determined that there are five main leaders that I need to take out to make the Bird Mafia collapse from within.")
sleep(delay)
print("Lil Nas X: Ah, yes. Well, to even make it to the Bird Mafia leaders, you will need to make your presence known. For that, I recommend you go talk to Bobby Hill. He moves around a lot, but rumors are that he is currently residing in NewNana.")
sleep(delay)
print("King Kong: Thank you. I need to go pay this Bobby Hill a visit.")
sleep(delay)
print("Australian Henriques: See ya later, yank.")
sleep(delay)
print("Narrator: You and Australian Henriques stroll out of the Seer's house, but when you get a few blocks away, a short, stocky bird beings approaching you. He is carrying a baton made out of a long, powerful looking feather.")
sleep(delay)
print("Australian Henriques: Kong... get behind me...")
sleep(delay)
print("Narrator: You dart behind Australian Henriques just as the bird reaches you, at which point you realize they are local law enforcement.")
sleep(delay)
print("Henchman: Hello boys, how are you today?")
sleep(delay)
print("Australian Henriques: Alright, but these damn Yanks are acting crazy.")
sleep(delay)
print("Narrator: At this point, the henchman holds up a picture of King Kong.")
sleep(delay)
print("Henchman: You boys wouldn't have happened to see this monkey around here, have you? Because he is wanted by the Bird Mafia.")
sleep(delay)
print("King Kong: I'm an ape, damn it!")
sleep(delay)
print("Narrator: You grab the henchman by his uniform, chucking him across the way. However, he is unfazed as you didn't damage him using the power of blackjack.")
sleep(delay)
print("Narrator: The henchman then pulls out his walkie talkie and calls for backup, before advancing on you himself.")
sleep(delay)
print("Henchman: Kong... you are going to regret pulling that maneuver.")
sleep(delay)
print("King Kong: Squawk, squawk then birdie... let's do this.")
sleep(delay)
henchman=classes.Henchman(classes.random_bird, 30, "Feather Baton")
sleep(delay)

fight(players_health,henchman,"Narrator: The henchman wacks you with his baton, grinning as he slowly defeats you.",'Narrator: King Kong and the henchman are at a standstil, trying to defeat one another.',"Australian Henriques: Watch out, this Yank's coming back for more.","Boom. Scumbag- down.")

print(f"Narrator: Your health is now {players_health}. !Good luck")
sleep(delay)
print("Narrator: Panting from your fight with the henchman, you look around to see police barricades, but you can't see how many policeman are blocking each exit.")
sleep(delay)
print("Australian Henriques: Right or left, mate?")
sleep(delay)
print("King Kong: I don't know...")
sleep(delay)
print("Australian Henriques: Mate, either make a decision or take your final L... but hurry up all the same.")
sleep(delay)
right_or_left = input("Narrator: Do you want to go right or left? One direction has more enemies than the other, but you will have to guess which. Right/Left: ").upper()
enforcer = classes.Enforcer(classes.random_bird, 50, "Feather SMG")

if right_or_left == "RIGHT":
    print("Narrator: Nice choice. As you and Australian Henriques run at the barricade, you see that 2 henchman and 1 enforcer are preventing your passage.")
    sleep(delay)
    print("Australian Henriques: One henchman each, mate, and then we'll handle the enforcer?")
    sleep(delay)
    print("King Kong: For sure.")
    sleep(delay)
    fight(players_health,henchman,"Narrator: The henchman wacks you with his baton, grinning as he slowly defeats you.",'Narrator: King Kong and the henchman are at a standstil, trying to defeat one another.',"Australian Henriques: Watch out, this Yank's coming back for more.","Boom. Scumbag- down.")
    sleep(delay)
    print("Narrator: You look over and see that, tragically, the enforcer has bested Australian Henriques after he [Australian Henriques] defeated a henchman.")
    sleep(delay)
    print("King Kong: No... Australian Henriques... You'll pay for this, bird.")
    sleep(delay)
    fight(players_health,enforcer,"Narrator: You grunt in pain as one of the enforcer's feather bullets pierces your skin.","Marrator: The battlefield is at a standstill. You and your opponent wait.","Australian Henriques: This guy sure is a fiesty one. He's probably a Brit.")

print('Finally, one last enforcer to take care of. ')
sleep(delay)
fight(players_health,enforcer,"Narrator: You grunt in pain as one of the enforcer's feather bullets pierces your skin.","Marrator: The battlefield is at a standstill. You and your opponent wait.","Australian Henriques: This guy sure is a fiesty one. He's probably a Brit.")
print("Narrator: You scoop up Australian Henriques, sprinting away from the police chasing you.")
sleep(delay)
print("Narrator: Once you have gained a good bit of distance between yourself and the Bird Mafia, you turn into a dark alleyway, trying to find a way to get Australian Henriques to a hospital without being noticed.")
sleep(delay)
print("Narrator: Just when you think you are safe, an ominous voice comes out of the back of the alleyway.")
sleep(delay)
print("Tweety: Well, well, well... look who it is...")
sleep(delay)
print("King Kong: Tweety - the first leader of the Bird Mafia... come to stop me, I suppose...")
sleep(delay)
print("Tweety: Listen, I'm just here to arrest you. We can do this peacefully, or violently, which will surely result in your friend failing to get the help he needs... it's your call.")
sleep(delay)
print("King Kong: If you think I'm willingly submitting to your regime, you've got something coming... tweet to your friends all you want, but I'll take down every leader in the Bird Mafia. You're just the first.")
sleep(delay)
print("Tweety: Fine by me... let's do this, you overgrown monkey.")
sleep(delay)
print("Narrator: Boss fights are a bit more difficult than fights against henchman or enforcers because you can't gamble more health than you have, but you will replenish any health you have lost after the fight.")
sleep(delay)
print(f"Narrator: For reference, you are currently on {players_health} health.")
sleep(delay)
Tweety = classes.Boss("Tweety", 100, "HAND", "Fruity Fields", True)
sleep(delay)

fight(players_health,Tweety,"Tweety: I tink I taw a puddycat... oh wait... it's just you.","Narrator: The battle is intense yet... no damage seems to be done.","King Kong: Revenge is a dish best served with yellow canary on top.","King Kong: One of five leaders down... gotta get Australian Henriques some medical treatment.")
print("Narrator: As you watch Tweety fall to the floor, defeated, you scoop up Australian Henriques and sprint towards the nearest hospital. However, halfway there, you are pulled into an alley.")
sleep(delay)
print("Nurse: Hello, Kong.")
sleep(delay)
print("Narrator: The nurse gestures to the room you are now in, which seems to be a cross between a hospital and a shop.")
sleep(delay)
print("Nurse: My associates and I lead a feeble branch of the resistance against the Bird Mafia. In each of the five main neighborhoods here in BananaLand, we have a branch of Resistance.Co, the name of our nonprofit. Here, let me take your friend to your hospital, and we can send him to meet you when he is healthy.")
sleep(delay)
print("Nurse: What is his name, and where should he meet you when he is ready?")
sleep(delay)
print("King Kong: His name is Australian Henriques. Please send him to Bobby Hill's house in NewNana when he is healthy.")
sleep(delay)
print("Nurse: Wonderful. Would you like to check out our shop now, perhaps buy some helpful weapons.")
sleep(delay)
print("Narrator: You travel to the shop room of the resistance base.")
sleep(delay)
print('Narrator: King Kong buys a drumset.')
sleep(delay)
print('King Kong: I did it Nas, I obtained the Drums of liberation.')
sleep(delay)
print('Australian Henriques: Crikey! That\'s the end of this story!' )
sleep('delay')
print("Izzy: Well, thats the end. I know its a bit of a cop-out ending, but I don't think you or I want to see this dumpsterfire of a story run for any longer.")